[package]
name = "ch06-enums-and-pattern-matching"
version = "0.1.0"
authors = ["Dani Guardiola <contact@daniguardiola.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
