[package]
name = "ch04-references-and-borrowing"
version = "0.1.0"
authors = ["Dani Guardiola <contact@daniguardiola.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
